version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "build(deps): ", which is
      # a conventional commit prefix and triggers release-please
      prefix: "build(deps)"
