language: rust
sudo: false
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - rust: nightly
      env: TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
  allow_failures:
  - rust: nightly
script:
  - travis-cargo build
  - travis-cargo test
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  travis-cargo doc &&
  travis-cargo --only stable doc-upload
env:
  global:
    secure: ujLBCE7iB7rMZaOSQQS0t7RjenxDnV/rtiMEB/aJnzbCBTo2RtJifyXkZci28YT0Sab8HeyCTsKafszgphj0BvSYUI8fwexPtRCXmgcLjouXRD0NWAr3dtEx0TPPXcwquer0BQzfeEZUmOnChKXDlcE3GSIdRSI+1Y8inbF4cRM=
