[package]
name = "bio"
version = "0.39.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A bioinformatics library for Rust. This library provides implementations of many algorithms and data structures that are useful for bioinformatics, but also in other fields."
homepage = "https://rust-bio.github.io"
repository = "https://github.com/rust-bio/rust-bio"
documentation = "https://docs.rs/bio"
readme = "README.md"
license = "MIT"
edition = "2018"
include = ["src/**/*", "LICENSE.md", "README.md", "CHANGELOG.md", "build.rs"]

[package.metadata.release]
pre-release-commit-message = "release version {{version}}"
tag-message = "Version {{version}} of Rust-Bio."

[features]
runtime-dispatch-simd = ["bytecount/runtime-dispatch-simd"]
generic-simd = ["bytecount/generic-simd"]
phylogeny = ["pest", "pest_derive", "bio-types/phylogeny"]

default = [
  "alignment",
  "alphabets",
  "data_structures",
  "io",
  "pattern_matching",
  "scores",
  "seq_analysis",
  "stats",
  "utils"
]

alignment = [
  # features
  "utils", "scores", "data_structures",
  # crates 
  "fxhash", "bio-types", "triple_accel", "petgraph",
]
alphabets = [
  # crates
  "bit-set", "lazy_static", "vec_map", "serde",
]
data_structures = [
  # features
  "alphabets", "utils",
  # crates
  "bytecount", "num-traits", "num-integer", "bv", "serde", "fxhash", "bio-types", "rand", "vec_map",
]
pattern_matching = [
  # features
  "utils", "alignment",
  # crates
  "num-traits", "stats", "ndarray", "vec_map",
]
scores = [
  # crates
  "ndarray", "lazy_static",
]
io = [
  # features
  "utils",
  # crates
  "csv", "itertools", "serde", "regex", "multimap", "approx", "bio-types", "anyhow", "petgraph",
]
seq_analysis = [
  # features
  "data_structures",
  # crates
  "approx",
]
stats = [
  # features
  "utils",
  # crates
  "num-traits", "itertools", "itertools-num", "ndarray", "lazy_static",
  "approx", "custom_derive", "newtype_derive", "ordered-float", "getset",
  "strum", "statrs", "enum-map", "serde",
]
utils = [
  # crates
  "num-traits", "serde",
]

[dependencies]
bytecount = { version = "0.6", optional = true }
csv = { version = "1.1", optional = true }
num-traits = { version = "0.2", optional = true }
num-integer = { version = "0.1", optional = true }
itertools = { version = ">= 0.8, < 0.11", optional = true }
itertools-num = { version = "0.1", optional = true }
bv = { version = "0.11", features = ["serde"], optional = true }
bit-set = { version = "0.5", optional = true }
ndarray = { version = ">=0.13, <0.16", optional = true }
lazy_static = { version = "1.4", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
approx = { version = ">=0.3, <0.6", optional = true }
custom_derive = { version = "0.1", optional = true }
newtype_derive = { version = "0.1", optional = true }
ordered-float = { version = "1.0", optional = true }
regex = { version = "1.3", default-features = false, features = ["std", "perf"], optional = true }
multimap = { version = ">=0.6, <0.9", optional = true }
fxhash = { version = "0.2", optional = true }
statrs = { version = ">= 0.11, < 0.16", optional = true }
bio-types = { version = ">=0.11.0", optional = true }
pest = { version = "2", optional = true }
pest_derive = { version = "2", optional = true }
strum = { version = ">= 0.16, < 0.24", optional = true, features = ["derive"] }
getset = { version = ">=0.0.9, <0.2", optional = true }
enum-map = { version = ">=0.6.4, <2", optional = true }
triple_accel = { version = ">=0.3, <0.5", optional = true }
thiserror = "1"
anyhow = { version = "1", optional =  true }
rand = { version = ">=0.7.3, < 0.9", optional = true }

[dependencies.vec_map]
version = "0.8"
features = ["eders"]
optional = true

[dependencies.petgraph]
version = ">=0.4, <0.7"
features = ["stable_graph"]
optional = true


[dev-dependencies]
proptest = "1"
tempfile = "3.1.0"
rand = "0.8.3"
approx = ">=0.3, <0.6"
